"""support resume library and soft delete

Revision ID: 5613c1f56e4d
Revises: 48a13f24856f
Create Date: 2026-08-26 14:31:22.357824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5613c1f56e4d'
down_revision: Union[str, Sequence[str], None] = '48a13f24856f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('file_content', sa.LargeBinary(), nullable=True))
    op.add_column('resumes', sa.Column('content_type', sa.String(length=100), nullable=True))
    op.add_column('resumes', sa.Column('is_deleted', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('resumes', 'is_deleted', server_default=None)
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_resumes_is_deleted'), 'resumes', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resumes_is_deleted'), table_name='resumes')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=True)
    op.drop_column('resumes', 'is_deleted')
    op.drop_column('resumes', 'content_type')
    op.drop_column('resumes', 'file_content')
    # ### end Alembic commands ###
