"""track enhanced resumes

Revision ID: 920c7265158c
Revises: 5613c1f56e4d
Create Date: 2026-08-26 14:45:44.878450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920c7265158c'
down_revision: Union[str, Sequence[str], None] = '5613c1f56e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('is_enhanced', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('resumes', 'is_enhanced', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_enhanced')
    # ### end Alembic commands ###
