"""Create career profiles table

Revision ID: 9612b3ed5a47
Revises: f97d3723bd0c
Create Date: 2026-08-22 17:41:36.710311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9612b3ed5a47'
down_revision: Union[str, Sequence[str], None] = 'f97d3723bd0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_role', sa.String(length=100), nullable=True),
    sa.Column('experience_years', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('target_location', sa.String(length=100), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('education', sa.JSON(), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('career_goals', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_master.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_profiles_user_id'), 'career_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_profiles_user_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    # ### end Alembic commands ###
