import { useEffect, useState } from "react";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import SectionHeader from "@/components/shared/SectionHeader";
import { useAuth } from "@/contexts/AuthContext";
import { deleteRoadmap, getRoadmap, saveRoadmap } from "@/services/roadmapService";

function RoadmapPage() { const { accessToken } = useAuth(); const [roadmap, setRoadmap] = useState(null); const [title, setTitle] = useState(""); const [description, setDescription] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { getRoadmap(accessToken).then((data) => { setRoadmap(data); setTitle(data.title); setDescription(data.description || ""); }).catch((err) => { if (err.response?.status !== 404) setError("Unable to load your roadmap."); }).finally(() => setLoading(false)); }, [accessToken]);
  async function submit(e) { e.preventDefault(); if (!title.trim()) return setError("A roadmap title is required."); setSaving(true); try { const data = await saveRoadmap({ title, description: description || null, status: "draft", items: roadmap?.items || [] }, accessToken); setRoadmap(data); } catch { setError("Unable to save your roadmap."); } finally { setSaving(false); } }
  async function remove() { if (!window.confirm("Delete this roadmap?")) return; try { await deleteRoadmap(accessToken); setRoadmap(null); setTitle(""); setDescription(""); } catch { setError("Unable to delete your roadmap."); } }
  if (loading) return <div className="p-8 text-slate-400">Loading your roadmap...</div>;
  return <div className="space-y-6"><Card className="border-white/10 bg-slate-900/70"><CardHeader><SectionHeader eyebrow="Roadmap" title={roadmap ? roadmap.title : "Create a roadmap"} description="Roadmaps are stored manually until AI generation is connected." /></CardHeader><CardContent><form onSubmit={submit} className="space-y-4"><input value={title} onChange={(e) => setTitle(e.target.value)} placeholder="Roadmap title" className="w-full rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3 text-white" /><textarea value={description} onChange={(e) => setDescription(e.target.value)} rows={4} placeholder="Description" className="w-full rounded-xl border border-white/10 bg-slate-950/70 px-4 py-3 text-white" />{error && <p className="text-sm text-red-300">{error}</p>}<div className="flex gap-3"><Button type="submit" disabled={saving}>{saving ? "Saving..." : roadmap ? "Update roadmap" : "Create roadmap"}</Button>{roadmap && <Button type="button" variant="outline" onClick={remove}>Delete</Button>}</div></form>{roadmap?.items?.length ? <div className="mt-6 space-y-3">{roadmap.items.map((item) => <div key={item.id} className="rounded-xl border border-white/10 bg-white/5 p-4 text-white"><p>{item.title}</p><p className="text-sm text-slate-400">{item.status}</p></div>)}</div> : <p className="mt-6 text-sm text-slate-400">No roadmap items yet.</p>}</CardContent></Card></div>;
}
export default RoadmapPage;